/* Generated By:JavaCC: Do not edit this line. HCISRConstants.java */
package hcisr;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HCISRConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 3;
  /** RegularExpression Id. */
  int END = 4;
  /** RegularExpression Id. */
  int OF = 5;
  /** RegularExpression Id. */
  int A = 6;
  /** RegularExpression Id. */
  int NAMED = 7;
  /** RegularExpression Id. */
  int TYPE = 8;
  /** RegularExpression Id. */
  int ARCHTYPE = 9;
  /** RegularExpression Id. */
  int EXTERNALTYPE = 10;
  /** RegularExpression Id. */
  int is_a_subtype_of = 11;
  /** RegularExpression Id. */
  int and_has = 12;
  /** RegularExpression Id. */
  int and_an_instance = 13;
  /** RegularExpression Id. */
  int understands_the_following_commands = 14;
  /** RegularExpression Id. */
  int which_initially_equals = 15;
  /** RegularExpression Id. */
  int is_created_with_the_commands = 16;
  /** RegularExpression Id. */
  int this_file_uses = 17;
  /** RegularExpression Id. */
  int this_file_describes = 18;
  /** RegularExpression Id. */
  int a_Class = 19;
  /** RegularExpression Id. */
  int Functions = 20;
  /** RegularExpression Id. */
  int a_Program = 21;
  /** RegularExpression Id. */
  int define_a = 22;
  /** RegularExpression Id. */
  int SET = 23;
  /** RegularExpression Id. */
  int TO = 24;
  /** RegularExpression Id. */
  int IF = 25;
  /** RegularExpression Id. */
  int TRUE = 26;
  /** RegularExpression Id. */
  int FALSE = 27;
  /** RegularExpression Id. */
  int otherwise = 28;
  /** RegularExpression Id. */
  int FOR_ALL = 29;
  /** RegularExpression Id. */
  int DO = 30;
  /** RegularExpression Id. */
  int WHILE = 31;
  /** RegularExpression Id. */
  int COMPLAIN_ABOUT = 32;
  /** RegularExpression Id. */
  int LABEL = 33;
  /** RegularExpression Id. */
  int GOTO = 34;
  /** RegularExpression Id. */
  int NOTE = 35;
  /** RegularExpression Id. */
  int RETURNS = 36;
  /** RegularExpression Id. */
  int RETURN = 37;
  /** RegularExpression Id. */
  int THEN = 38;
  /** RegularExpression Id. */
  int IN = 39;
  /** RegularExpression Id. */
  int AS = 40;
  /** RegularExpression Id. */
  int WITH = 41;
  /** RegularExpression Id. */
  int STRINGREF = 42;
  /** RegularExpression Id. */
  int INTREF = 43;
  /** RegularExpression Id. */
  int FLOATREF = 44;
  /** RegularExpression Id. */
  int FUNCTIONREF = 45;
  /** RegularExpression Id. */
  int BOOLREF = 46;
  /** RegularExpression Id. */
  int make_a_new = 47;
  /** RegularExpression Id. */
  int and_in_the_event_of_a = 48;
  /** RegularExpression Id. */
  int the_following_functions_make_use_of = 49;
  /** RegularExpression Id. */
  int IDENT = 50;
  /** RegularExpression Id. */
  int NUMS = 51;
  /** RegularExpression Id. */
  int LP = 52;
  /** RegularExpression Id. */
  int RP = 53;
  /** RegularExpression Id. */
  int CHARS = 54;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<EOL>",
    "\".\"",
    "\"of\"",
    "\"a\"",
    "\"named\"",
    "\"type\"",
    "\"archtype\"",
    "\"external type\"",
    "\"is a subtype of\"",
    "\"and has\"",
    "\"and an instance\"",
    "\"understands the following commands\"",
    "\"which initially equals\"",
    "\"is created with the commands\"",
    "\"this file uses\"",
    "\"this file describes\"",
    "\"a class\"",
    "\"functions\"",
    "\"a program\"",
    "\"define a\"",
    "\"set\"",
    "\"to\"",
    "\"if\"",
    "\"true\"",
    "\"false\"",
    "\"otherwise\"",
    "\"for all\"",
    "\"do\"",
    "\"while\"",
    "\"complain about\"",
    "\"label\"",
    "\"go to\"",
    "\"note\"",
    "\"returns\"",
    "\"return\"",
    "\"then\"",
    "\"in\"",
    "\"as\"",
    "\"with\"",
    "<STRINGREF>",
    "\"Integer:\"",
    "\"Float:\"",
    "\"Function:\"",
    "\"Boolean:\"",
    "\"make a new\"",
    "\"and in the event of a\"",
    "\"the following functions make use of\"",
    "<IDENT>",
    "<NUMS>",
    "\"(\"",
    "\")\"",
    "<CHARS>",
  };

}
